version: '2'
services:
  ledstrip:
    build: .
    command: node index.js
    volumes: 
      - .:/app
      - /app/node_modules
      - /var/run/dbus/:/var/run/dbus/:z
    ports:
      - "5000:5000"