version: '3.8'
services:
  ledstrip:
    container_name: elk-bledom-recode
    build: .
    command: node index.js
    privileged: true
    network_mode: host
    volumes: 
      - .:/app
      - /app/node_modules
      - /var/run/dbus/:/var/run/dbus/:rw
      - /run/dbus:/run/dbus/:rw
    ports:
      - "5000:5000"